blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.home, name="home"),
    path("detail/<int:pk>/", views.post_detail, name="detail"),
    path("new-post/", views.new_post, name="new_post"),
    path("update-post/<int:pk>/", views.update_post, name="update_post"),
    path("delete/<int:pk>/", views.delete_post, name="post_delete"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("user-posts/<str:username>/", views.one_user_post, name="user_post"),
    path("notifications/", views.notifications, name="notifications"),
    path("new-feed/", views.new_feed, name="new_feed"),

]

django_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path("user/", include("userauths.urls")),

    # Account Reset URLs
    path("password-reset/", auth_views.PasswordResetView.as_view(template_name="userauths/password_reset.html"), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

userauths/urls.py
from django.urls import path

from . import views
app_name = "userauths"

urlpatterns = [
    path("signup/", views.register, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/", views.profile, name="profile"),
]

templates/partials/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>{% block title %}{% endblock title %} | Verified💯</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <!--// Font Awesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.0.0/css/all.css" integrity="sha384-3B6NwesSXE7YJlcLI9RpRqGf2p/EgVH8BgoKTaUrmKNDkHPStTQ3EyoYjCGXaOTS" crossorigin="anonymous" />
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top flex">
      <div class="container flex">
          <div class="">
              <a class="navbar-brand mr-4" href="/">Verified💯</a>
          </div>
          <div class="center-navbar">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                      aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse justify-content-between" id="navbarToggle">
                  <div class="navbar-nav flex">
                      <a class="nav-item nav-link" href="{% url 'blog:dashboard' %}">
                    <span class="dashboard-flex flex">
                        <span><i class="fa fa-bar-chart"></i></span>&nbsp; Dashboard
                    </span>
                      </a>
                      <!-- Notification -->
                      <!--  <div class="flex">-->
                      <div id="notification-icon">
                          <a class="nav-item nav-link" href="">
                              {% if user.is_authenticated %}
                              <span class="badge badge-pill badge-danger notification-badge">{{ user.notifications.unread.count }}</span>
                              {% endif %}
                              <i class="fa fa-bell"></i> Notifications
                          </a>
                      </div>
                      <a class="nav-item nav-link" href="">about</a>
                      <!--   </div>-->
                  </div>
              </div>
          </div>
        <!-- Navbar Right Side -->
      <div class="flex">
          <div class="navbar-nav ms-auto">
              {% if request.user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'blog:new_post' %}">New Post</a>
              <a class="nav-item nav-link" href="{% url 'userauths:profile' %}">Profile</a>
              <a class="nav-item nav-link" href="{% url 'userauths:logout' %}">Logout</a>
              <div class="px-4 profile-image d-flex align-items-center">
                  <img width="30px" height="30px" style="border-radius:50%;" src="{{ user.profile.image.url }}" alt="">
                  <a class="nav-item nav-link" href="">@{{ user.username }}</a>
              </div>
              {% else %}
              <a class="nav-item nav-link" href="{% url 'userauths:login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'userauths:signup' %}">Register</a>
              {% endif %}
          </div>
      </div>
    </div>
    </div>
  </nav>
  {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
            <strong>{{message}}</strong>
        </div>
    {% endfor %}
  {% endif %}
<main role="main" class="container">
  <div class="row mt-5 flat">
    <div class="col-md-8">
      {% block content %}{% endblock %}
    </div>
<!--      Sidebar starts here -->
    <div class="col-md-4">
      <div class="content-section">
        <h3>Our Sidebar</h3>
        <p class='text-muted'>You can put any information here you'd like.
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">Latest Posts</li>
            <li class="list-group-item list-group-item-light">Announcements</li>
            <li class="list-group-item list-group-item-light">Calendars</li>
            <li class="list-group-item list-group-item-light">etc</li>
          </ul>
        </p>
      </div>
    </div>
<!--      Sidebar ends here -->
  </div>
</main>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>


<!-- In your base.html, after the closing </body> tag -->
<footer class="footer mt-auto py-5 bg-dark text-light">
    <div class="container text-center">
        <div class="row">
            <div class="col-md-4">
                <h5>Connect with Us</h5>
                <!-- Add social media icons or links here using Material Icons -->
                <span class="material-icons">facebook</span>
                <span class="material-icons">cloud</span>
                <span class="material-icons">draw</span>
            </div>
            <div class="col-md-4">
                <h5>Amenities</h5>
                <!-- Add various amenities icons using Material Icons -->
                <span class="material-icons">wifi</span>
                <span class="material-icons">local_parking</span>
                <span class="material-icons">pool</span>
            </div>
            <div class="col-md-4">
                <h5>Contact</h5>
                <p>Email: info@VerifiedDating.com</p>
                <p>Phone: +8 (123) 983-7840</p>
            </div>
        </div>
        <hr class="my-4">
        <span class="text-white-muted border-bottom">Verified💯 &copy; 2024</span>
    </div>
</footer>
</body>
</html>

templates/partials/sidebar.html
    <div class="col-md-4">
      <div class="content-section">
        <h3>Our Sidebar</h3>
        <p class='text-muted'>You can put any information here you'd like.
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">Latest Posts</li>
            <li class="list-group-item list-group-item-light">Announcements</li>
            <li class="list-group-item list-group-item-light">Calendars</li>
            <li class="list-group-item list-group-item-light">etc</li>
          </ul>
        </p>
      </div>
    </div>