blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.home, name="home"),
    path("detail/<int:pk>/", views.post_detail, name="detail"),
    path("new-post/", views.new_post, name="new_post"),
    path("update-post/<int:pk>/", views.update_post, name="update_post"),
    path("delete/<int:pk>/", views.delete_post, name="post_delete"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("user-posts/<str:username>/", views.one_user_post, name="user_post"),
    path("notifications/", views.notifications, name="notifications"),
    path("new-feed/", views.new_feed, name="new_feed"),

]

django_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path("user/", include("userauths.urls")),

    # Account Reset URLs
    path("password-reset/", auth_views.PasswordResetView.as_view(template_name="userauths/password_reset.html"), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, related_name="posts", on_delete=models.CASCADE)

    class Meta:
        ordering = ["-date_posted"]

    def __str__(self):
        return self.title


class Feed(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, related_name="feeds", on_delete=models.CASCADE)
    image = models.ImageField(upload_to="feed_pics", null=True, blank=True)

    class Meta:
        ordering = ["-date_posted"]

    def __str__(self):
        return self.title


# Comment
class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    author = models.ForeignKey(User, related_name="comments", on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text


# Notification Model
class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message

blog/forms.py
from django import forms

from .models import Post, Comment, Feed


class NewPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content"]


class NewFeedForm(forms.ModelForm):
    class Meta:
        model = Feed
        fields = ["title", "content", "image"]



class UpdatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from .models import Post, Comment, Notification, Feed
from .forms import NewPostForm, UpdatePostForm, CommentForm, NewFeedForm



def home(request):
    posts = Post.objects.all()

    context = {"posts": posts}
    return render(request, "blog/home.html", context)


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    comments = Comment.objects.filter(post=post)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            # return redirect("blog:detail", pk=post.id)
    else:
        form = CommentForm()

    context = {
        "post": post,
        "comments": comments,
        "form": form,
    }
    return render(request, "blog/post_detail.html", context)


@login_required
def new_post(request):
    if request.method == "POST":
        form = NewPostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("blog:home")
    else:
        form = NewPostForm()
    context = {
        "form": form,
        "title": "Create Post"
    }
    return render(request, "blog/form.html", context)


@login_required
def update_post(request, pk):
    post = Post.objects.get(pk=pk)

    if request.user != post.author:
        return redirect("blog:detail", pk=post.id)

    if request.method == "POST":
        form = UpdatePostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect("blog:detail", pk=post.id)
    else:
        form = UpdatePostForm(instance=post)
    context = {
        "form": form,
        "post": post,
        "title": "Update Post"
    }
    return render(request, "blog/form.html", context)


@login_required
def delete_post(request, pk):
    post = get_object_or_404(Post, pk=pk, created_by=request.user)

    if request.user != post.author:
        return redirect("blog:home")

    if request.method == "POST":
        post.delete()
        return redirect("blog:home")

    context = {
        "post": post,
    }
    return render(request, "blog/post_delete.html", context)


@login_required
def dashboard(request):
    user_posts = Post.objects.filter(author=request.user)
    context = {
        "posts": user_posts,
    }
    return render(request, "blog/dashboard.html", context)


def one_user_post(request, username):
    post_author = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=post_author)
    post_count = posts.count()
    context = {
        "posts": posts,
        "post_author": post_author,
        "post_count": post_count,
    }
    return render(request, "blog/user_post.html", context)


# Notification view
@login_required
def notifications(request):
    user = request.user
    user_notifications = Notification.objects.filter(user=user, is_read=False)

    context = {
        "user_notifications": user_notifications,
    }
    return render(request, "blog/notifications.html", context)


@login_required
def new_feed(request):
    if request.method == "POST":
        form = NewFeedForm(request.POST)
        if form.is_valid():
            feed = form.save(commit=False)
            feed.author = request.user
            feed.save()
            return redirect("blog:home")
    else:
        form = NewFeedForm()
    context = {
        "form": form,
        "title": "Create Post"
    }
    return render(request, "blog/feed.html", context)

templates/blog/dashboard.html
{% extends 'partials/base.html' %}

{% block content %}
<h1 class="mb-3">Posts by {{ user.username }}</h1> <!-- ({{ page_obj.paginator.count }})-->
{% for post in posts %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{% url 'blog:dashboard' %}">{{ post.author }}</a>
            <small class="text-muted">{{ post.date_posted|date:"F d, Y"}}</small>
        </div>
        <h2><a class="article-title" href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
{% endfor %}
<!--{% if is_paginated %}-->

<!--    {% if page_obj.has_previous %}-->
<!--    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>-->
<!--    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>-->

<!--    {% endif %}-->

<!--    {% for num in page_obj.paginator.page_range %}-->
<!--        {% if page_obj.number == num %}-->
<!--            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>-->
<!--        {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3" %}-->
<!--            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>-->
<!--        {% endif %}-->
<!--    {% endfor %}-->

<!--    {% if page_obj.has_next %}-->
<!--    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>-->
<!--    <a class="btn btn-outline-dark mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>-->
<!--    {% endif %}-->

<!--{% endif %}-->
{% endblock content%}

templates/blog/feed.html
{% extends "partials/base.html" %}
{% block title %}Feed{% endblock title %}
{% block content %}
<h1>Home page</h1>
<div class="row">
    {% for post in feed %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
        <div class="media-body">

            <div class="article-metadata">
                <a class="mr-2 text-decoration-none"
                   href="#">{{post.author}}</a>
                <small class="text-muted"> | {{post.date_posted|date:"F d Y"}}</small>
            </div>
            <h2><a class="article-title" href="#">{{post.title}}</a></h2>
            <p class="article-content">
                <a class="text-decoration-none text-muted" href="#">{% if
                    post.content|wordcount > 50 %}{{ post.content|truncatewords:50 }} "Read More"{% else %} {{
                    post.content }}{% endif %}</a>
            </p>
            <div>
                <img src="{{ feed.image.url }}" alt="" style="width: 20rem;">
            </div>
        </div>
    </article>
</div>
    {% endfor %}

{% endblock content %}
____________

templates/blog/form.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                 {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">{{title}}</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/blog/home.html
{% extends 'partials/base.html' %}
{% block title %}Home{% endblock title %}

{% block content %}
<!--<h1>Home</h1>-->
{% for post in posts %}

<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
    <div class="media-body">

        <div class="article-metadata">
            <a class="mr-2 text-decoration-none"
               href="{% url 'blog:user_post' post.author.username %}">{{post.author}}</a>
            <small class="text-muted"> | {{post.date_posted|date:"F d Y"}}</small>
        </div>
        <h2><a class="article-title" href="{% url 'blog:detail' post.id %}">{{post.title}}</a></h2>
        <p class="article-content">
            <a class="text-decoration-none text-muted" href="{% url 'blog:detail' post.id %}">{% if post.content|wordcount > 50 %}{{ post.content|truncatewords:50 }} "Read More"{% else %} {{ post.content }}{% endif %}</a>
        </p>
    </div>
</article>

{% endfor %}


{% endblock content %}

templates/blog/notifications.html
{% extends 'partials/base.html' %}
{% block title %}{{user.username}}'s Notifications{% endblock title %}
{% block content %}
<h1 class="mb-3">@{{ user.username }}'s Notifications</h1> <!-- ({{ page_obj.paginator.count }})-->
{% for post in posts %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2 text-decoration-none text-black">{{ post.author }}</a>
            <small class="text-muted"> | {{ post.date_posted|date:"F d, Y"}}</small>
        </div>
        <h2><a class="article-title" href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content|truncatewords:100 }}</p>
    </div>
</article>
{% endfor %}

{% endblock content%}

templates/blog/post_delete.html
{% extends 'partials/base.html' %}
{% block title %}Delete "{{ post.title|truncatewords:2 }}"{% endblock title %}

{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete '{{ post.title }}'?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'blog:detail' post.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

templates/blog/post_detail.html
{% extends 'partials/base.html' %}
{% block title %}{{post.title|truncatewords:3}}{% endblock title %}
{% block content %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
    <div>
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="">{{ post.author }}</a>
                <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
                {% if post.author == request.user %}
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blog:update_post' post.id %}">Update</a>
                    <a class="btn btn-warning btn-sm mt-1 mb-1" href="{% url 'blog:post_delete' post.id %}">Delete</a>
                </div>
                {% endif %}
            </div>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
            <hr>
        </div>

        <!--Comment functionality-->
        <div class="comment">
            <h4>Comments</h4>
            {% for comment in comments %}
                <div class="comment-detail">
                    <img class="account-img" src="{{comment.author.profile.image.url}}" alt="">
                    <span>
                        <p>@{{ comment.author }} | {{ comment.created_at }}</p>
                        <p>{{ comment.text }}</p>
                    </span>
                </div>
            {% endfor %}
        </div>
    </div>
</article>
{% endblock content%}

templates/blog/user_post.html
{% extends 'partials/base.html' %}
{% block title %}{{post_author.username}}'s Posts{% endblock title %}
{% block content %}
<h1 class="mb-3">Posts by {{ post_author.username }} ({{post_count}} posts)</h1> <!-- ({{ page_obj.paginator.count }})-->
{% for post in posts %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2 text-decoration-none text-black">{{ post.author }}</a>
            <small class="text-muted"> | {{ post.date_posted|date:"F d, Y"}}</small>
        </div>
        <h2><a class="article-title" href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content|truncatewords:100 }}</p>
    </div>
</article>
{% endfor %}
<!--{% if is_paginated %}-->

<!--    {% if page_obj.has_previous %}-->
<!--    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>-->
<!--    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>-->

<!--    {% endif %}-->

<!--    {% for num in page_obj.paginator.page_range %}-->
<!--        {% if page_obj.number == num %}-->
<!--            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>-->
<!--        {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3" %}-->
<!--            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>-->
<!--        {% endif %}-->
<!--    {% endfor %}-->

<!--    {% if page_obj.has_next %}-->
<!--    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>-->
<!--    <a class="btn btn-outline-dark mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>-->
<!--    {% endif %}-->

<!--{% endif %}-->
{% endblock content%}